/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index'
import { Route as authSignInImport } from './routes/(auth)/sign-in'
import { Route as authOtpImport } from './routes/(auth)/otp'
import { Route as auth500Import } from './routes/(auth)/500'

// Create Virtual Routes

const errors503LazyImport = createFileRoute('/(errors)/503')()
const errors500LazyImport = createFileRoute('/(errors)/500')()
const errors404LazyImport = createFileRoute('/(errors)/404')()
const errors403LazyImport = createFileRoute('/(errors)/403')()
const errors401LazyImport = createFileRoute('/(errors)/401')()
const authSignUpLazyImport = createFileRoute('/(auth)/sign-up')()
const authForgotPasswordLazyImport = createFileRoute(
  '/(auth)/forgot-password',
)()
const AuthenticatedSettingsRouteLazyImport = createFileRoute(
  '/_authenticated/settings',
)()
const AuthenticatedUsersIndexLazyImport = createFileRoute(
  '/_authenticated/users/',
)()
const AuthenticatedSettingsIndexLazyImport = createFileRoute(
  '/_authenticated/settings/',
)()
const AuthenticatedFeedbackIndexLazyImport = createFileRoute(
  '/_authenticated/feedback/',
)()
const AuthenticatedEmployeeIndexLazyImport = createFileRoute(
  '/_authenticated/employee/',
)()
const AuthenticatedCustomersIndexLazyImport = createFileRoute(
  '/_authenticated/customers/',
)()
// const AuthenticatedCarsIndexLazyImport = createFileRoute(
//   '/_authenticated/cars/',
// )()
const AuthenticatedServicesIndexLazyImport = createFileRoute(
  '/_authenticated/services/',
)()
const AuthenticatedAdminsIndexLazyImport = createFileRoute(
  '/_authenticated/admins/',
)()
const AuthenticatedSettingsNotificationsLazyImport = createFileRoute(
  '/_authenticated/settings/notifications',
)()
const AuthenticatedSettingsDisplayLazyImport = createFileRoute(
  '/_authenticated/settings/display',
)()
const AuthenticatedSettingsAppearanceLazyImport = createFileRoute(
  '/_authenticated/settings/appearance',
)()
const AuthenticatedSettingsAccountLazyImport = createFileRoute(
  '/_authenticated/settings/account',
)()
const AuthenticatedCustomersCustomerCarsByPhoneIndexLazyImport =
  createFileRoute('/_authenticated/customers/$customerCarsByPhone/')()
const AuthenticatedproductsOilIndexLazyImport = createFileRoute(
  '/_authenticated/(products)/oil/',
)()
const AuthenticatedproductsLiquidIndexLazyImport = createFileRoute(
  '/_authenticated/(products)/liquid/',
)()
const AuthenticatedproductsAntifreezeIndexLazyImport = createFileRoute(
  '/_authenticated/(products)/antifreeze/',
)()
const AuthenticatedCustomersCustomerCarsByPhoneCustomerCarIdIndexLazyImport =
  createFileRoute(
    '/_authenticated/customers/$customerCarsByPhone/$customerCarId/',
  )()

// Create/Update Routes

const AuthenticatedRouteRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const errors503LazyRoute = errors503LazyImport
  .update({
    id: '/(errors)/503',
    path: '/503',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/503.lazy').then((d) => d.Route))

const errors500LazyRoute = errors500LazyImport
  .update({
    id: '/(errors)/500',
    path: '/500',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/500.lazy').then((d) => d.Route))

const errors404LazyRoute = errors404LazyImport
  .update({
    id: '/(errors)/404',
    path: '/404',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/404.lazy').then((d) => d.Route))

const errors403LazyRoute = errors403LazyImport
  .update({
    id: '/(errors)/403',
    path: '/403',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/403.lazy').then((d) => d.Route))

const errors401LazyRoute = errors401LazyImport
  .update({
    id: '/(errors)/401',
    path: '/401',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/401.lazy').then((d) => d.Route))

const authSignUpLazyRoute = authSignUpLazyImport
  .update({
    id: '/(auth)/sign-up',
    path: '/sign-up',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(auth)/sign-up.lazy').then((d) => d.Route))

const authForgotPasswordLazyRoute = authForgotPasswordLazyImport
  .update({
    id: '/(auth)/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() =>
    import('./routes/(auth)/forgot-password.lazy').then((d) => d.Route),
  )

const AuthenticatedSettingsRouteLazyRoute =
  AuthenticatedSettingsRouteLazyImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/route.lazy').then((d) => d.Route),
  )

const authSignInRoute = authSignInImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const authOtpRoute = authOtpImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRoute,
} as any)

const auth500Route = auth500Import.update({
  id: '/(auth)/500',
  path: '/500',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedUsersIndexLazyRoute =
  AuthenticatedUsersIndexLazyImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/users/index.lazy').then((d) => d.Route),
  )

const AuthenticatedSettingsIndexLazyRoute =
  AuthenticatedSettingsIndexLazyImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/index.lazy').then((d) => d.Route),
  )

const AuthenticatedFeedbackIndexLazyRoute =
  AuthenticatedFeedbackIndexLazyImport.update({
    id: '/feedback/',
    path: '/feedback/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/feedback/index.lazy').then((d) => d.Route),
  )

const AuthenticatedEmployeeIndexLazyRoute =
  AuthenticatedEmployeeIndexLazyImport.update({
    id: '/employee/',
    path: '/employee/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/employee/index.lazy').then((d) => d.Route),
  )

const AuthenticatedCustomersIndexLazyRoute =
  AuthenticatedCustomersIndexLazyImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/customers/index.lazy').then((d) => d.Route),
  )

// const AuthenticatedCarsIndexLazyRoute = AuthenticatedCarsIndexLazyImport.update(
//   {
//     id: '/cars/',
//     path: '/cars/',
//     getParentRoute: () => AuthenticatedRouteRoute,
//   } as any,
// ).lazy(() =>
//   import('./routes/_authenticated/cars/index.lazy').then((d) => d.Route),
//)
const AuthenticatedServicesIndexLazyRoute = AuthenticatedServicesIndexLazyImport.update(
  {
    id: '/services/',
    path: '/services/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any,
).lazy(() =>
  import('./routes/_authenticated/services/index.lazy').then((d) => d.Route),
)

const AuthenticatedAdminsIndexLazyRoute =
  AuthenticatedAdminsIndexLazyImport.update({
    id: '/admins/',
    path: '/admins/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/admins/index.lazy').then((d) => d.Route),
  )

const AuthenticatedSettingsNotificationsLazyRoute =
  AuthenticatedSettingsNotificationsLazyImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/notifications.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedSettingsDisplayLazyRoute =
  AuthenticatedSettingsDisplayLazyImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/display.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedSettingsAppearanceLazyRoute =
  AuthenticatedSettingsAppearanceLazyImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/appearance.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedSettingsAccountLazyRoute =
  AuthenticatedSettingsAccountLazyImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/account.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedCustomersCustomerCarsByPhoneIndexLazyRoute =
  AuthenticatedCustomersCustomerCarsByPhoneIndexLazyImport.update({
    id: '/customers/$customerCarsByPhone/',
    path: '/customers/$customerCarsByPhone/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import(
      './routes/_authenticated/customers/$customerCarsByPhone/index.lazy'
    ).then((d) => d.Route),
  )

const AuthenticatedproductsOilIndexLazyRoute =
  AuthenticatedproductsOilIndexLazyImport.update({
    id: '/(products)/oil/',
    path: '/oil/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/(products)/oil/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedproductsLiquidIndexLazyRoute =
  AuthenticatedproductsLiquidIndexLazyImport.update({
    id: '/(products)/liquid/',
    path: '/liquid/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/(products)/liquid/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedproductsAntifreezeIndexLazyRoute =
  AuthenticatedproductsAntifreezeIndexLazyImport.update({
    id: '/(products)/antifreeze/',
    path: '/antifreeze/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/(products)/antifreeze/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedCustomersCustomerCarsByPhoneCustomerCarIdIndexLazyRoute =
  AuthenticatedCustomersCustomerCarsByPhoneCustomerCarIdIndexLazyImport.update({
    id: '/customers/$customerCarsByPhone/$customerCarId/',
    path: '/customers/$customerCarsByPhone/$customerCarId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import(
      './routes/_authenticated/customers/$customerCarsByPhone/$customerCarId/index.lazy'
    ).then((d) => d.Route),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/500': {
      id: '/(auth)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof auth500Import
      parentRoute: typeof rootRoute
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordLazyImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpLazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503LazyImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountLazyImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceLazyImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayLazyImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsLazyImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/_authenticated/admins/': {
      id: '/_authenticated/admins/'
      path: '/admins'
      fullPath: '/admins'
      preLoaderRoute: typeof AuthenticatedAdminsIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    // '/_authenticated/cars/': {
    //   id: '/_authenticated/cars/'
    //   path: '/cars'
    //   fullPath: '/cars'
    //   preLoaderRoute: typeof AuthenticatedCarsIndexLazyImport
    //   parentRoute: typeof AuthenticatedRouteImport
    // }
    '/_authenticated/services/': {
      id: '/_authenticated/services/'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AuthenticatedServicesIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/employee/': {
      id: '/_authenticated/employee/'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof AuthenticatedEmployeeIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/feedback/': {
      id: '/_authenticated/feedback/'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AuthenticatedFeedbackIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexLazyImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/(products)/antifreeze/': {
      id: '/_authenticated/(products)/antifreeze/'
      path: '/antifreeze'
      fullPath: '/antifreeze'
      preLoaderRoute: typeof AuthenticatedproductsAntifreezeIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/(products)/liquid/': {
      id: '/_authenticated/(products)/liquid/'
      path: '/liquid'
      fullPath: '/liquid'
      preLoaderRoute: typeof AuthenticatedproductsLiquidIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/(products)/oil/': {
      id: '/_authenticated/(products)/oil/'
      path: '/oil'
      fullPath: '/oil'
      preLoaderRoute: typeof AuthenticatedproductsOilIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/customers/$customerCarsByPhone/': {
      id: '/_authenticated/customers/$customerCarsByPhone/'
      path: '/customers/$customerCarsByPhone'
      fullPath: '/customers/$customerCarsByPhone'
      preLoaderRoute: typeof AuthenticatedCustomersCustomerCarsByPhoneIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/customers/$customerCarsByPhone/$customerCarId/': {
      id: '/_authenticated/customers/$customerCarsByPhone/$customerCarId/'
      path: '/customers/$customerCarsByPhone/$customerCarId'
      fullPath: '/customers/$customerCarsByPhone/$customerCarId'
      preLoaderRoute: typeof AuthenticatedCustomersCustomerCarsByPhoneCustomerCarIdIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedSettingsRouteLazyRouteChildren {
  AuthenticatedSettingsAccountLazyRoute: typeof AuthenticatedSettingsAccountLazyRoute
  AuthenticatedSettingsAppearanceLazyRoute: typeof AuthenticatedSettingsAppearanceLazyRoute
  AuthenticatedSettingsDisplayLazyRoute: typeof AuthenticatedSettingsDisplayLazyRoute
  AuthenticatedSettingsNotificationsLazyRoute: typeof AuthenticatedSettingsNotificationsLazyRoute
  AuthenticatedSettingsIndexLazyRoute: typeof AuthenticatedSettingsIndexLazyRoute
}

const AuthenticatedSettingsRouteLazyRouteChildren: AuthenticatedSettingsRouteLazyRouteChildren =
  {
    AuthenticatedSettingsAccountLazyRoute:
      AuthenticatedSettingsAccountLazyRoute,
    AuthenticatedSettingsAppearanceLazyRoute:
      AuthenticatedSettingsAppearanceLazyRoute,
    AuthenticatedSettingsDisplayLazyRoute:
      AuthenticatedSettingsDisplayLazyRoute,
    AuthenticatedSettingsNotificationsLazyRoute:
      AuthenticatedSettingsNotificationsLazyRoute,
    AuthenticatedSettingsIndexLazyRoute: AuthenticatedSettingsIndexLazyRoute,
  }

const AuthenticatedSettingsRouteLazyRouteWithChildren =
  AuthenticatedSettingsRouteLazyRoute._addFileChildren(
    AuthenticatedSettingsRouteLazyRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteLazyRoute: typeof AuthenticatedSettingsRouteLazyRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminsIndexLazyRoute: typeof AuthenticatedAdminsIndexLazyRoute
  AuthenticatedServicesIndexLazyRoute: typeof AuthenticatedServicesIndexLazyRoute
  //AuthenticatedCarsIndexLazyRoute: typeof AuthenticatedCarsIndexLazyRoute
  AuthenticatedCustomersIndexLazyRoute: typeof AuthenticatedCustomersIndexLazyRoute
  AuthenticatedEmployeeIndexLazyRoute: typeof AuthenticatedEmployeeIndexLazyRoute
  AuthenticatedFeedbackIndexLazyRoute: typeof AuthenticatedFeedbackIndexLazyRoute
  AuthenticatedUsersIndexLazyRoute: typeof AuthenticatedUsersIndexLazyRoute
  AuthenticatedproductsAntifreezeIndexLazyRoute: typeof AuthenticatedproductsAntifreezeIndexLazyRoute
  AuthenticatedproductsLiquidIndexLazyRoute: typeof AuthenticatedproductsLiquidIndexLazyRoute
  AuthenticatedproductsOilIndexLazyRoute: typeof AuthenticatedproductsOilIndexLazyRoute
  AuthenticatedCustomersCustomerCarsByPhoneIndexLazyRoute: typeof AuthenticatedCustomersCustomerCarsByPhoneIndexLazyRoute
  AuthenticatedCustomersCustomerCarsByPhoneCustomerCarIdIndexLazyRoute: typeof AuthenticatedCustomersCustomerCarsByPhoneCustomerCarIdIndexLazyRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteLazyRoute:
    AuthenticatedSettingsRouteLazyRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminsIndexLazyRoute: AuthenticatedAdminsIndexLazyRoute,
  AuthenticatedServicesIndexLazyRoute: AuthenticatedServicesIndexLazyRoute,
  AuthenticatedCustomersIndexLazyRoute: AuthenticatedCustomersIndexLazyRoute,
  AuthenticatedEmployeeIndexLazyRoute: AuthenticatedEmployeeIndexLazyRoute,
  AuthenticatedFeedbackIndexLazyRoute: AuthenticatedFeedbackIndexLazyRoute,
  AuthenticatedUsersIndexLazyRoute: AuthenticatedUsersIndexLazyRoute,
  AuthenticatedproductsAntifreezeIndexLazyRoute:
    AuthenticatedproductsAntifreezeIndexLazyRoute,
  AuthenticatedproductsLiquidIndexLazyRoute:
    AuthenticatedproductsLiquidIndexLazyRoute,
  AuthenticatedproductsOilIndexLazyRoute:
    AuthenticatedproductsOilIndexLazyRoute,
  AuthenticatedCustomersCustomerCarsByPhoneIndexLazyRoute:
    AuthenticatedCustomersCustomerCarsByPhoneIndexLazyRoute,
  AuthenticatedCustomersCustomerCarsByPhoneCustomerCarIdIndexLazyRoute:
    AuthenticatedCustomersCustomerCarsByPhoneCustomerCarIdIndexLazyRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedRouteRouteWithChildren
  '/500': typeof errors500LazyRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/settings': typeof AuthenticatedSettingsRouteLazyRouteWithChildren
  '/forgot-password': typeof authForgotPasswordLazyRoute
  '/sign-up': typeof authSignUpLazyRoute
  '/401': typeof errors401LazyRoute
  '/403': typeof errors403LazyRoute
  '/404': typeof errors404LazyRoute
  '/503': typeof errors503LazyRoute
  '/': typeof AuthenticatedIndexRoute
  '/settings/account': typeof AuthenticatedSettingsAccountLazyRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceLazyRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayLazyRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsLazyRoute
  '/admins': typeof AuthenticatedAdminsIndexLazyRoute
  //'/cars': typeof AuthenticatedCarsIndexLazyRoute
  '/services': typeof AuthenticatedServicesIndexLazyRoute
  '/customers': typeof AuthenticatedCustomersIndexLazyRoute
  '/employee': typeof AuthenticatedEmployeeIndexLazyRoute
  '/feedback': typeof AuthenticatedFeedbackIndexLazyRoute
  '/settings/': typeof AuthenticatedSettingsIndexLazyRoute
  '/users': typeof AuthenticatedUsersIndexLazyRoute
  '/antifreeze': typeof AuthenticatedproductsAntifreezeIndexLazyRoute
  '/liquid': typeof AuthenticatedproductsLiquidIndexLazyRoute
  '/oil': typeof AuthenticatedproductsOilIndexLazyRoute
  '/customers/$customerCarsByPhone': typeof AuthenticatedCustomersCustomerCarsByPhoneIndexLazyRoute
  '/customers/$customerCarsByPhone/$customerCarId': typeof AuthenticatedCustomersCustomerCarsByPhoneCustomerCarIdIndexLazyRoute
}

export interface FileRoutesByTo {
  '/500': typeof errors500LazyRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/forgot-password': typeof authForgotPasswordLazyRoute
  '/sign-up': typeof authSignUpLazyRoute
  '/401': typeof errors401LazyRoute
  '/403': typeof errors403LazyRoute
  '/404': typeof errors404LazyRoute
  '/503': typeof errors503LazyRoute
  '/': typeof AuthenticatedIndexRoute
  '/settings/account': typeof AuthenticatedSettingsAccountLazyRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceLazyRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayLazyRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsLazyRoute
  '/admins': typeof AuthenticatedAdminsIndexLazyRoute
  '/services': typeof AuthenticatedServicesIndexLazyRoute
  //'/cars': typeof AuthenticatedCarsIndexLazyRoute
  '/customers': typeof AuthenticatedCustomersIndexLazyRoute
  '/employee': typeof AuthenticatedEmployeeIndexLazyRoute
  '/feedback': typeof AuthenticatedFeedbackIndexLazyRoute
  '/settings': typeof AuthenticatedSettingsIndexLazyRoute
  '/users': typeof AuthenticatedUsersIndexLazyRoute
  '/antifreeze': typeof AuthenticatedproductsAntifreezeIndexLazyRoute
  '/liquid': typeof AuthenticatedproductsLiquidIndexLazyRoute
  '/oil': typeof AuthenticatedproductsOilIndexLazyRoute
  '/customers/$customerCarsByPhone': typeof AuthenticatedCustomersCustomerCarsByPhoneIndexLazyRoute
  '/customers/$customerCarsByPhone/$customerCarId': typeof AuthenticatedCustomersCustomerCarsByPhoneCustomerCarIdIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/500': typeof auth500Route
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteLazyRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordLazyRoute
  '/(auth)/sign-up': typeof authSignUpLazyRoute
  '/(errors)/401': typeof errors401LazyRoute
  '/(errors)/403': typeof errors403LazyRoute
  '/(errors)/404': typeof errors404LazyRoute
  '/(errors)/500': typeof errors500LazyRoute
  '/(errors)/503': typeof errors503LazyRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountLazyRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceLazyRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayLazyRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsLazyRoute
  '/_authenticated/admins/': typeof AuthenticatedAdminsIndexLazyRoute
  '/_authenticated/services/': typeof AuthenticatedServicesIndexLazyRoute
  //'/_authenticated/cars/': typeof AuthenticatedCarsIndexLazyRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexLazyRoute
  '/_authenticated/employee/': typeof AuthenticatedEmployeeIndexLazyRoute
  '/_authenticated/feedback/': typeof AuthenticatedFeedbackIndexLazyRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexLazyRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexLazyRoute
  '/_authenticated/(products)/antifreeze/': typeof AuthenticatedproductsAntifreezeIndexLazyRoute
  '/_authenticated/(products)/liquid/': typeof AuthenticatedproductsLiquidIndexLazyRoute
  '/_authenticated/(products)/oil/': typeof AuthenticatedproductsOilIndexLazyRoute
  '/_authenticated/customers/$customerCarsByPhone/': typeof AuthenticatedCustomersCustomerCarsByPhoneIndexLazyRoute
  '/_authenticated/customers/$customerCarsByPhone/$customerCarId/': typeof AuthenticatedCustomersCustomerCarsByPhoneCustomerCarIdIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/500'
    | '/otp'
    | '/sign-in'
    | '/settings'
    | '/forgot-password'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/503'
    | '/'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/admins'
    | '/services'
    | '/customers'
    | '/employee'
    | '/feedback'
    | '/settings/'
    | '/users'
    | '/antifreeze'
    | '/liquid'
    | '/oil'
    | '/customers/$customerCarsByPhone'
    | '/customers/$customerCarsByPhone/$customerCarId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/500'
    | '/otp'
    | '/sign-in'
    | '/forgot-password'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/503'
    | '/'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/admins'
    | '/services'
    | '/customers'
    | '/employee'
    | '/feedback'
    | '/settings'
    | '/users'
    | '/antifreeze'
    | '/liquid'
    | '/oil'
    | '/customers/$customerCarsByPhone'
    | '/customers/$customerCarsByPhone/$customerCarId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/500'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/admins/'
    //| '/_authenticated/cars/'
    | '/_authenticated/services/'
    | '/_authenticated/customers/'
    | '/_authenticated/employee/'
    | '/_authenticated/feedback/'
    | '/_authenticated/settings/'
    | '/_authenticated/users/'
    | '/_authenticated/(products)/antifreeze/'
    | '/_authenticated/(products)/liquid/'
    | '/_authenticated/(products)/oil/'
    | '/_authenticated/customers/$customerCarsByPhone/'
    | '/_authenticated/customers/$customerCarsByPhone/$customerCarId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  auth500Route: typeof auth500Route
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authForgotPasswordLazyRoute: typeof authForgotPasswordLazyRoute
  authSignUpLazyRoute: typeof authSignUpLazyRoute
  errors401LazyRoute: typeof errors401LazyRoute
  errors403LazyRoute: typeof errors403LazyRoute
  errors404LazyRoute: typeof errors404LazyRoute
  errors500LazyRoute: typeof errors500LazyRoute
  errors503LazyRoute: typeof errors503LazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  auth500Route: auth500Route,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authForgotPasswordLazyRoute: authForgotPasswordLazyRoute,
  authSignUpLazyRoute: authSignUpLazyRoute,
  errors401LazyRoute: errors401LazyRoute,
  errors403LazyRoute: errors403LazyRoute,
  errors404LazyRoute: errors404LazyRoute,
  errors500LazyRoute: errors500LazyRoute,
  errors503LazyRoute: errors503LazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/(auth)/500",
        "/(auth)/otp",
        "/(auth)/sign-in",
        "/(auth)/forgot-password",
        "/(auth)/sign-up",
        "/(errors)/401",
        "/(errors)/403",
        "/(errors)/404",
        "/(errors)/500",
        "/(errors)/503"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated/route.tsx",
      "children": [
        "/_authenticated/settings",
        "/_authenticated/",
        "/_authenticated/admins/",
        "/_authenticated/cars/",
        "/_authenticated/customers/",
        "/_authenticated/employee/",
        "/_authenticated/feedback/",
        "/_authenticated/users/",
        "/_authenticated/(products)/antifreeze/",
        "/_authenticated/(products)/liquid/",
        "/_authenticated/(products)/oil/",
        "/_authenticated/customers/$customerCarsByPhone/",
        "/_authenticated/customers/$customerCarsByPhone/$customerCarId/"
      ]
    },
    "/(auth)/500": {
      "filePath": "(auth)/500.tsx"
    },
    "/(auth)/otp": {
      "filePath": "(auth)/otp.tsx"
    },
    "/(auth)/sign-in": {
      "filePath": "(auth)/sign-in.tsx"
    },
    "/_authenticated/settings": {
      "filePath": "_authenticated/settings/route.lazy.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/settings/account",
        "/_authenticated/settings/appearance",
        "/_authenticated/settings/display",
        "/_authenticated/settings/notifications",
        "/_authenticated/settings/"
      ]
    },
    "/(auth)/forgot-password": {
      "filePath": "(auth)/forgot-password.lazy.tsx"
    },
    "/(auth)/sign-up": {
      "filePath": "(auth)/sign-up.lazy.tsx"
    },
    "/(errors)/401": {
      "filePath": "(errors)/401.lazy.tsx"
    },
    "/(errors)/403": {
      "filePath": "(errors)/403.lazy.tsx"
    },
    "/(errors)/404": {
      "filePath": "(errors)/404.lazy.tsx"
    },
    "/(errors)/500": {
      "filePath": "(errors)/500.lazy.tsx"
    },
    "/(errors)/503": {
      "filePath": "(errors)/503.lazy.tsx"
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/settings/account": {
      "filePath": "_authenticated/settings/account.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/appearance": {
      "filePath": "_authenticated/settings/appearance.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/display": {
      "filePath": "_authenticated/settings/display.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/notifications": {
      "filePath": "_authenticated/settings/notifications.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/admins/": {
      "filePath": "_authenticated/admins/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/cars/": {
      "filePath": "_authenticated/cars/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/customers/": {
      "filePath": "_authenticated/customers/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/employee/": {
      "filePath": "_authenticated/employee/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/feedback/": {
      "filePath": "_authenticated/feedback/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/settings/": {
      "filePath": "_authenticated/settings/index.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/users/": {
      "filePath": "_authenticated/users/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/(products)/antifreeze/": {
      "filePath": "_authenticated/(products)/antifreeze/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/(products)/liquid/": {
      "filePath": "_authenticated/(products)/liquid/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/(products)/oil/": {
      "filePath": "_authenticated/(products)/oil/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/customers/$customerCarsByPhone/": {
      "filePath": "_authenticated/customers/$customerCarsByPhone/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/customers/$customerCarsByPhone/$customerCarId/": {
      "filePath": "_authenticated/customers/$customerCarsByPhone/$customerCarId/index.lazy.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
